// 단어 데이터 (자동 생성: data/words.json → 이 파일)
// 수정은 data/words.json 을 고친 뒤 `npm run build:words` 로 재생성하세요.

export const WORDS = [
  {
    es: "equipaje",
    kr: "에끼빠헤",
    koReading: "짐, 수하물",
    meaning: "여행 가방 등 부치는 짐 전체를 가리키는 말.",
    scene: "체크인·수하물 찾는 곳",
  },
  {
    es: "pasaporte",
    kr: "빠사뽀르떼",
    koReading: "여권",
    meaning: "해외 여행에 필요한 신분증명서.",
    scene: "출입국 심사대",
  },
  {
    es: "vuelo",
    kr: "부엘로",
    koReading: "항공편, 비행",
    meaning: "비행기 편명이나 운항을 가리키는 말.",
    scene: "탑승 안내판",
  },
  {
    es: "aduana",
    kr: "아두아나",
    koReading: "세관",
    meaning: "물품 반입을 검사하는 곳.",
    scene: "입국장 세관 통과",
  },
  {
    es: "maleta",
    kr: "말레따",
    koReading: "캐리어(여행 가방)",
    meaning: "바퀴 달린 여행용 가방.",
    scene: "수하물 찾는 곳",
  },
  {
    es: "habitación",
    kr: "아비따시온",
    koReading: "방(객실)",
    meaning: "호텔이나 숙소의 방.",
    scene: "체크인·객실 안내",
  },
  {
    es: "recepción",
    kr: "레셉시온",
    koReading: "프런트, 리셉션",
    meaning: "숙소 입구의 안내 데스크.",
    scene: "체크인·문의할 때",
  },
  {
    es: "llave",
    kr: "야베",
    koReading: "열쇠",
    meaning: "방문을 여는 열쇠나 카드키.",
    scene: "체크인 후 방 열쇠 받을 때",
  },
  {
    es: "toalla",
    kr: "또아야",
    koReading: "수건",
    meaning: "몸을 닦는 데 쓰는 천.",
    scene: "객실 비품 요청",
  },
  {
    es: "desayuno",
    kr: "데사유노",
    koReading: "아침식사",
    meaning: "하루의 첫 끼니.",
    scene: "조식 포함 여부 확인",
  },
  {
    es: "menú",
    kr: "메누",
    koReading: "메뉴",
    meaning: "음식 종류를 적어놓은 판.",
    scene: "자리에 앉아 주문 준비",
  },
  {
    es: "cuenta",
    kr: "꾸엔따",
    koReading: "계산서",
    meaning: "식사 후 지불할 금액이 적힌 종이.",
    scene: "식사를 마치고 계산할 때",
  },
  {
    es: "propina",
    kr: "쁘로삐나",
    koReading: "팁",
    meaning: "서비스에 대한 감사의 의미로 더 주는 돈.",
    scene: "식당·택시 등에서 팁 문화 확인",
  },
  {
    es: "agua",
    kr: "아구아",
    koReading: "물",
    meaning: "마시는 물.",
    scene: "음료 주문할 때",
  },
  {
    es: "picante",
    kr: "삐깐떼",
    koReading: "매운",
    meaning: "맵다는 뜻의 형용사.",
    scene: "음식 맛 정도를 물을 때",
  },
  {
    es: "rebaja",
    kr: "레바하",
    koReading: "세일, 할인",
    meaning: "가격을 낮춘 판매.",
    scene: "세일 기간 쇼핑",
  },
  {
    es: "probador",
    kr: "쁘로바도르",
    koReading: "탈의실",
    meaning: "옷을 입어보는 공간.",
    scene: "옷가게에서 착용 요청 후",
  },
  {
    es: "efectivo",
    kr: "에펙띠보",
    koReading: "현금",
    meaning: "지폐나 동전으로 된 돈.",
    scene: "결제 수단을 말할 때",
  },
  {
    es: "talla",
    kr: "따야",
    koReading: "사이즈, 치수",
    meaning: "옷이나 신발의 크기.",
    scene: "옷 사이즈 문의",
  },
  {
    es: "recibo",
    kr: "레시보",
    koReading: "영수증",
    meaning: "결제했다는 증명서.",
    scene: "계산 후 환불·교환 대비",
  },
  {
    es: "hospital",
    kr: "오스삐딸",
    koReading: "병원",
    meaning: "치료를 받는 의료 기관.",
    scene: "아프거나 다쳤을 때",
  },
  {
    es: "farmacia",
    kr: "파르마시아",
    koReading: "약국",
    meaning: "약을 사는 곳.",
    scene: "간단한 약이 필요할 때",
  },
  {
    es: "policía",
    kr: "뽈리시아",
    koReading: "경찰",
    meaning: "치안을 담당하는 공무원(또는 경찰서).",
    scene: "도난·사고 신고",
  },
  {
    es: "izquierda",
    kr: "이스끼에르다",
    koReading: "왼쪽",
    meaning: "방향을 나타내는 왼쪽.",
    scene: "길 안내를 들을 때",
  },
  {
    es: "derecha",
    kr: "데레차",
    koReading: "오른쪽",
    meaning: "방향을 나타내는 오른쪽.",
    scene: "길 안내를 들을 때",
  },
  {
    es: "amigo",
    kr: "아미고",
    koReading: "친구(남성)",
    meaning: "가까운 사이의 사람.",
    scene: "누군가를 소개할 때",
  },
  {
    es: "trabajo",
    kr: "뜨라바호",
    koReading: "일, 직장",
    meaning: "하는 일이나 직장.",
    scene: "자기소개할 때",
  },
  {
    es: "tiempo",
    kr: "띠엠뽀",
    koReading: "시간, 날씨",
    meaning: "문맥에 따라 시간 또는 날씨를 뜻함.",
    scene: "시간이나 날씨를 물을 때",
  },
  {
    es: "familia",
    kr: "파밀리아",
    koReading: "가족",
    meaning: "부모·형제 등 가까운 혈연.",
    scene: "가족을 소개할 때",
  },
  {
    es: "dinero",
    kr: "디네로",
    koReading: "돈",
    meaning: "화폐, 돈.",
    scene: "비용을 이야기할 때",
  },
  {
    es: "embarazada",
    kr: "엠바라사다",
    koReading: "임신한",
    guess: "영어 embarrassed(당황한)와 철자가 비슷해 착각하기 쉬움",
    real: "임신한 (pregnant)",
  },
  {
    es: "actualmente",
    kr: "악뚜알멘떼",
    koReading: "현재",
    guess: "영어 actually(사실은)와 비슷해 보여 착각하기 쉬움",
    real: "현재, 요즘 (currently)",
  },
  {
    es: "éxito",
    kr: "엑시또",
    koReading: "성공",
    guess: "영어 exit(출구)와 철자가 비슷해 착각하기 쉬움",
    real: "성공 (success)",
  },
  {
    es: "constipado",
    kr: "꼰스띠빠도",
    koReading: "코감기",
    guess: "영어 constipated(변비인)와 비슷해 보여 착각하기 쉬움",
    real: "감기에 걸려 코가 막힌 (having a cold)",
  },
  {
    es: "sopa",
    kr: "소빠",
    koReading: "수프",
    guess: "영어 soap(비누)와 발음이 비슷해 착각하기 쉬움",
    real: "수프, 국물 요리 (soup)",
  },
  {
    es: "carpeta",
    kr: "까르뻬따",
    koReading: "폴더",
    guess: "영어 carpet(카펫)과 철자가 비슷해 착각하기 쉬움",
    real: "서류철, 폴더 (folder)",
  },
  {
    es: "ropa",
    kr: "로빠",
    koReading: "옷",
    guess: "영어 rope(밧줄)와 발음이 비슷해 착각하기 쉬움",
    real: "옷, 의류 (clothes)",
  },
  {
    es: "librería",
    kr: "리브레리아",
    koReading: "서점",
    guess: "영어 library(도서관)와 철자가 비슷해 착각하기 쉬움",
    real: "서점 (bookstore) — 도서관은 biblioteca",
  },
  {
    es: "sensible",
    kr: "센시블레",
    koReading: "예민한",
    guess: "영어 sensible(분별있는)과 철자가 같아 착각하기 쉬움",
    real: "예민한, 민감한 (sensitive)",
  },
  {
    es: "largo",
    kr: "라르고",
    koReading: "긴",
    guess: "영어 large(큰)와 비슷해 보여 착각하기 쉬움",
    real: "긴, 길이가 긴 (long) — '큰'은 grande",
  },
];

export const WORD_TOTAL = WORDS.length;
